### ISSUE TITLE
ButtonView font getting cut off

### ISSUE THREAD

**Issue by joshwinter** [gameclosure/devkit#106]
Hi,

I'm trying to put together a ButtonView using slices. Everything works great in the simulator, but when I view it on the iPhone, the letters are getting cut off. 
It's only happening when using the padding attribute, which I need for proper vertical alignment with custom fonts because of the font leading (space above the font).

Here is a test project I put together. The button is on the 2nd tab. Please ignore the first tab.
http://www.mediafire.com/download/2alr0jw2t6wzmla/listTest.zip

Thanks much!

**Comment by collingreen** [comment]
Closing this for now. Please re-open if this is still an issue.
