### ISSUE TITLE
Can't Build Android APK

### ISSUE THREAD

**Issue by Harry30000** [gameclosure/devkit#112]
Hi all,

I have install Devkit and try to debug with "basil debug native-android" command but can't. 

I try to install again with the same way but still have bug. I'm using Win 8.
I don't known what kind of bug , how to solve that, please help me. 

Thanks

![bug](https://f.cloud.github.com/assets/5426701/1122013/a7287cd0-1acf-11e3-9e31-eede8974cdc8.png)

**Comment by jwilm** [comment]
This issue was related to devkit-v1. As we update for devkit2, such issues are being closed as "likely to be fixed in devkit2". If the issue persists after updating, please reopen it. Thank you!
