### ISSUE TITLE
Registration form provided by installation script requires permission to access

### ISSUE THREAD

**Issue by csantosbh** [gameclosure/devkit#141]
The registration form link https://docs.google.com/a/gameclosure.com/forms/d/1zYBFvzAlmZX4JWmWY1RkPxYlRJXUszLs4aWu2nt_kPs/viewform (provided by the installation script) leads to a google form page that requires permission to access.

**Comment by jwilm** [comment]
This issue was related to devkit-v1. As we update for devkit2, such issues are being closed as "likely to be fixed in devkit2". If the issue persists after updating, please reopen it. Thank you!
