### ISSUE TITLE
ndk-build errors

### ISSUE THREAD

**Issue by AlexanderPatuk** [gameclosure/devkit#187]
![build errors](https://cloud.githubusercontent.com/assets/1439459/4557343/88a5b222-4ed2-11e4-8701-09ec5777a743.png)
Fatal errors apeared when ndk-build runs :
  [ndk-build]   jni/js/js_context.cpp:637:33: error: narrowing conversion of 'g'
from 'double' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp:637:33: error: narrowing conversion of 'b'
from 'double' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp:637:33: error: narrowing conversion of 'a'
from 'double' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp: In function 'v8::Handle<v8::Value> defFill
TextBitmapDeprecated(const v8::Arguments&)':
 [ndk-build]   jni/js/js_context.cpp:735:49: error: narrowing conversion of 'x1'
 from 'int' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]                    rect_2d src_rect = {x1, y1, w, h};
 [ndk-build]                                                    ^
 [ndk-build]   jni/js/js_context.cpp:735:49: error: narrowing conversion of 'y1'
 from 'int' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp:735:49: error: narrowing conversion of 'w'
from 'int' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp:735:49: error: narrowing conversion of 'h'
from 'int' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]   jni/js/js_context.cpp:736:64: error: narrowing conversion of 'x'
from 'double' to 'float' inside { } is ill-formed in C++11 [-Werror=narrowing]
 [ndk-build]                    rect_2d dest_rect = {x, y, w * scale, h * scale}

Used the latest version from Git

**Comment by jwilm** [comment]
This is fixed in the newer version with `static_cast<float>`
