### ISSUE TITLE
Error: Target id is not valid. Use 'android list targets' to get the target ids.

### ISSUE THREAD

**Issue by marlncpe** [gameclosure/devkit#19]
root@marlon-laptop:/home/marlon/devkit/projects/whack-that-mole# basil build native-android --no-compress --debug --clean
     [build]    Building: debug/native-android
[build-native]    Writing resources for 7ba6726c608a43fd8b607d27841e2774 with target native-android
   [android]    [error]  Submodule tealeaf-core not found
      [jsio]    Inferring opts from platform: native
  [packager]    native-android { appID: '7ba6726c608a43fd8b607d27841e2774',
  version: undefined,
  fullPath: '/home/marlon/devkit/projects/whack-that-mole',
  compress: false,
  debug: true,
  release: true,
  servicesURL: 'http://api.gameclosure.com',
  output: '/home/marlon/devkit/addons/native-android/build/whackthatmole/assets/resources',
  localBuildPath: 'build/debug/native-android',
  isSimulated: false,
  isTestApp: false,
  noRedirect: false,
  noPrompt: true,
  packageName: '',
  studio: 'lilvarmit.com',
  metadata: null,
  target: 'native-android',
  subtarget: 'android' }
      [jsio]    Compiling Source code.
      [jsio]    jsio_compile "gc.native.launchClient" --cwd "/home/marlon/devkit/projects/whack-that-mole" --compressorCachePath "/home/marlon/devkit/projects/whack-that-mole/build/.cache" --printOutput  --defines "{\"BUILD_TARGET\":\"native-android\",\"BUILD_ENV\":\"native\",\"DEBUG\":true,\"DEV_MODE\":true,\"ADDON_NATIVE_ANDROID2\":true,\"ADDON_EXAMPLES\":true,\"ADDON_NATIVE_ANDROID\":true}" --jsioPath "sdk/jsio" --noIE "true" --environment "native" --path "[\".\",\"sdk/jsio\",\"sdk/gc/api/\",\"sdk/\",\"sdk/timestep/\"]" --includeJsio "true" --appendImport "false" --debug "4"
WARN preprocessors.compiler could not compile import from sdk/gc/native/launchClient.js: 'import base', {}).logging.get('console'
WARN preprocessors.compiler could not compile import from sdk/timestep/device.js: 'import ui.backend.' + (exports.useDOM ? 'dom' : 'canvas'
LOG ..**imports** Including native runtime.
      [make]   ndk-build -C TeaLeaf clean
make[1]: Entering directory `/home/marlon/devkit/addons/native-android/TeaLeaf'
Clean: andprof [armeabi]
Clean: cpufeatures [armeabi]
Clean: jansson [armeabi]
Clean: jpeg [armeabi]
Clean: png [armeabi]
Clean: stdc++ [armeabi]
Clean: tealeaf [armeabi]
Clean: v8a [armeabi]
Clean: zip [armeabi]
Clean: andprof [armeabi-v7a]
Clean: cpufeatures [armeabi-v7a]
Clean: jansson [armeabi-v7a]
Clean: jpeg [armeabi-v7a]
Clean: png [armeabi-v7a]
Clean: stdc++ [armeabi-v7a]
Clean: tealeaf [armeabi-v7a]
Clean: v8a [armeabi-v7a]
Clean: zip [armeabi-v7a]
make[1]: Leaving directory`/home/marlon/devkit/addons/native-android/TeaLeaf'
ant -f TeaLeaf/build.xml clean
      [make]   Buildfile: /home/marlon/devkit/addons/native-android/TeaLeaf/build.xml
   [android]   Error: Target id is not valid. Use 'android list targets' to get the target ids.
(android exited with code 1)
   [android]    [error]  build failed creating android project
   [android]    [error]  1

please help me :(

**Comment by voghDev** [comment]
I am having a similar error in my Android project (four years later :joy:  but anyway Google brought me here so it's okay to comment, maybe it helps someone). I had to update all versions in my `travis.yml` file:

    android:
      components:
        - tools
        - platform-tools
        - build-tools-25.0.3
        - android-25
        - extra-google-m2repository
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-24
    
    before_script:
      - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
      - emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell settings put global window_animation_scale 0 &
      - adb shell settings put global transition_animation_scale 0 &
      - adb shell settings put global animator_duration_scale 0 &
          - adb shell input keyevent 82 &

You can track the changes [here](https://github.com/voghDev/PdfViewPager/blob/update_doc/.travis.yml)

**Comment by akarsh** [comment]
@voghDev your mentioned changes solve my errors in travis-cI.
thank you
