### ISSUE TITLE
atob and btoa functions support in native-android & native-ios

### ISSUE THREAD

**Issue by aigninja** [gameclosure/devkit#194]
Hi,

I need atob and btoa native functions in nativeandroid & native-ios for encoding. I have read from docs, devkit uses v8 and spidermonkey. In nativeInspector, when i try to test atob/btob function it crashes.  Is there any way to get these functions?

**Comment by jwilm** [comment]
This issue was related to devkit-v1. As we update for devkit2, such issues are being closed as "likely to be fixed in devkit2". If the issue persists after updating, please reopen it. Thank you!
