### ISSUE TITLE
Can't preview or Can't load game

### ISSUE THREAD

**Issue by jgamao** [gameclosure/devkit#196]
I make a new project but I can't preview or load the game but my other project can and I don't know the problem and to solve it. 

There are errors appear:

-XMLHttpRequest cannot load http://localhost/socket.io/?EIO=3&transport=polling&t=1422434605793-65. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9200' is therefore not allowed access. The response had HTTP status code 404.

 -Uncaught ReferenceError: Transportsport is not defined

- Uncaught RangeError: Maximum call stack size exceeded

-ERROR ...interfaces SyntaxError: Unexpected token ' {stack: (...), message: "Unexpected token '"}interfaces.js:120 exports.Connector.exports.Connector.onConnectpostmessage.js:108 exports.Connector.exports.Connector._onMessagebase.js:85 __bound

**Comment by jwilm** [comment]
This issue was related to devkit-v1. As we update for devkit2, such issues are being closed as "likely to be fixed in devkit2". If the issue persists after updating, please reopen it. Thank you!

**Comment by jgamao** [comment]
Thank you for helping. I have solved it.
