### ISSUE TITLE
Install instructions Linux

### ISSUE THREAD

**Issue by jwilm** [gameclosure/devkit#200]
_Originally posted by @jishnu7 before the devkit2 repo merge_

Asking users to change ownership of a system folder is a bad advice.

Instead ask to create `npmrc`, point npm global to a folder in user's home directory and add this location to `PATH`.

# ~/.npmrc
`prefix = /home/user_name/.npm-bin`

# .bashrc or .zshrc
`PATH=$PATH:/home/user_name/.npm-bin`

now `npm install -g devkit` will work without root permission.

**Comment by collingreen** [comment]
Updated the wiki with this as the first installation option
