### ISSUE TITLE
devkit release native-android build error

### ISSUE THREAD

**Issue by jgamao** [gameclosure/devkit#207]
I can't create a release for my app in my ubuntu 14.04. 

There are build errors when I command devkit release native-android:

 [ndk-build]    ndk-build -j 8 RELEASE=1
      [android]    android create project --target android-15 --name calamity_run --path /home/joselito/wt-calamityrun/build/release/native-android --activity calamity_runActivity --package com.wetalkdirect.studio.calamity_run
Android NDK: WARNING: APP_PLATFORM android-15 is larger than android:minSdkVersion 8 in ./AndroidManifest.xml    
    [ndk-build]   Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries    
    [ndk-build]   Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries    
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_animate.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_build.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_console.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_context.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_device.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_dialog.cpp
    [ndk-build]   [armeabi] Compile++ thumb: tealeaf <= js_events.cpp
    [ndk-build]   jni/js/js_animate.cpp:17:24: fatal error: core/types.h: No such file or directoryIn file included from jni/js/js_events.cpp:17:0:
jni/js/js_events.h:17:30: fatal error: core/util/detect.h: No such file or directory

compilation terminated.
compilation terminated.
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_events.o] Error 1
    [ndk-build]   make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_animate.o] Error 1
    [ndk-build]   jni/js/js.cpp:21:30: fatal error: core/util/detect.h: No such file or directory
compilation terminated.
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js.o] Error 1
    [ndk-build]   In file included from jni/js/js_dialog.h:18:0,
                 from jni/js/js_dialog.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
In file included from jni/js/js_build.h:17:0,
                 from jni/js/js_build.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_build.o] Error 1
    [ndk-build]   In file included from jni/js/js_context.h:18:0,
                 from jni/js/js_context.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
    [ndk-build]   In file included from jni/js/js_device.h:15:0,
                 from jni/js/js_device.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
    [ndk-build]   In file included from jni/js/js_console.h:18:0,
                 from jni/js/js_console.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
    [ndk-build]   compilation terminated.
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_device.o] Error 1
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_console.o] Error 1
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_dialog.o] Error 1
    [ndk-build]   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_context.o] Error 1
        [build]    [error]  build failed
        [build]    [error]  2
        [build]    2 minutes, 17.59 seconds elapsed
Error: Project folder '/home/joselito/wt-calamityrun/build/release/native-android' is not empty. Please consider using 'android update' instead.
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/src/com/wetalkdirect/studio/calamity_run
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/src/com/wetalkdirect/studio/calamity_run/calamity_runActivity.java
Created directory /home/joselito/wt-calamityrun/build/release/native-android/res
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/bin
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/libs
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/values
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/res/values/strings.xml
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/layout
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/res/layout/main.xml
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-hdpi
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-mdpi
      [android]   Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-ldpi
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/AndroidManifest.xml
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/build.xml
      [android]   Added file /home/joselito/wt-calamityrun/build/release/native-android/proguard-project.txt
      [android]    android update project --target android-15 --path /home/joselito/wt-calamityrun/build/release/native-android --library ../../../modules/devkit-core/modules/native-android/TeaLeaf
Resolved location of library project to: /home/joselito/wt-calamityrun/modules/devkit-core/modules/native-android/TeaLeaf
      [android]   Updated project.properties
      [android]   Updated local.properties
      [android]   Updated file /home/joselito/wt-calamityrun/build/release/native-android/proguard-project.txt
[native-android]    No plugin XML to inject
[native-android]    Applying final XSL transformation
[native-android]    [error]  settings for AndroidManifest: value for icons is not a string
     [jvmtools]    connected to localhost:35765

**Comment by jwilm** [comment]
The `core` symlink is missing in your native-android folder.

**Comment by jgamao** [comment]
What is symlink?

**Comment by jgamao** [comment]
What's the core symlink?

**Comment by farleyknight** [comment]
@jgamao Did you solve this? I just got this error.

**Comment by jwilm** [comment]
@farleyknight There's supposed to be a symlink under `native-android/TeaLeaf/jni` named `core` which points to `native-android/native-core`.

**Comment by DenisGold** [comment]
Hi! Please HELP!!!! I have same issue.......
 [jvmtools]    connected to localhost:62677
[native-resources]    writing 8 files to /Users/dartius/Documents/IOS-Games/orioGame/build/debug/native-android/assets/resources
    [ndk-build]    ndk-build -j 8 DEBUG=1
      [android]    android create project --target android-19 --name orioGame --path /Users/dartius/Documents/IOS-Games/orioGame/build/debug/native-android --activity orioGameActivity --package com.example.studio.orioGame
    [ndk-build]    Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 8 in ./AndroidManifest.xml    
                   Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries    
                   Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries    
                   [armeabi] Compile++ thumb: tealeaf <= js.cpp
                   [armeabi] Compile++ thumb: tealeaf <= js_animate.cpp
                   [armeabi] Compile++ thumb: tealeaf <= js_build.cpp
                   jni/js/js_animate.cpp:17:24: fatal error: core/types.h: No such file or directory
                    #include "core/types.h"
                                           ^
                   compilation terminated.
                   
                   
                   [armeabi] Compile++ thumb: tealeaf <= js_console.cpp
                   jni/js/js.cpp:21:30: fatal error: core/util/detect.h: No such file or directory
                    #include "core/util/detect.h"
                                                 ^
                   compilation terminated.
                   *** [obj/local/armeabi/objs-debug/tealeaf/js/js.o] Error 1
                   In file included from jni/js/js_build.h:17:0,
                                    from jni/js/js_build.cpp:17:
                   jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
                    #include "core/core_js.h"
                                             ^
                   compilation terminated.
                   
                   In file included from jni/js/js_console.h:18:0,
                                    from jni/js/js_console.cpp:17:
                   jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
                    #include "core/core_js.h"
                                             ^
                   compilation terminated.
                   make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_console.o] Error 1

PLEASE HELP!!!!!!!!

**Comment by jwilm** [comment]
The [above comment](https://github.com/gameclosure/devkit/issues/207#issuecomment-90094099) explains how to fix the errors you're having.
