### ISSUE TITLE
Init with default .gitignore files

### ISSUE THREAD

**Issue by oodavid** [gameclosure/devkit#215]
Since GC is git centric, does it make sense to have a default .gitignore that prevent the various build files from being included?:

```
sdk/
build/
modules/
```

**Comment by rampr** [comment]
yeah, makes sense :)

**Comment by jwilm** [comment]
Will merge if someone can put up a PR :+1:

**Comment by collingreen** [comment]
These are already in the default devkit application template (not sdk, since that is devkit1 only), but had not yet made it into the devkit repo. 

This should fix it:
https://github.com/gameclosure/devkit/commit/3109406c9b46e67980656bc34769124a82e6decc
