### ISSUE TITLE
Game Closure DevKit Plugin: Billing

### ISSUE THREAD

**Issue by jgamao** [gameclosure/devkit#219]
Hello,

I have a problem installing the billing plugin in my project. Is  "basil install billing "  still the way to install or there's another way?

JGamao

**Comment by jwilm** [comment]
Have you upgraded to devkit 2? If so, you can run `devkit install https://github.com/gameclosure/billing` from your project folder.

**Comment by collingreen** [comment]
Closing this unless there is a problem with installing the latest billing plugin using devkit2. Please reopen if necessary.

**Comment by jgamao** [comment]
thank you @jwilm for the information.. I got it!!
