### ISSUE TITLE
devkit not working in Linux 

### ISSUE THREAD

**Issue by dave-watts** [gameclosure/devkit#222]
Hi

When I follow the instructions for OSX/Linux 

"Run devkit init mygame to create the mygame folder and install the dependencies.
Run devkit serve to start the simulator"

The emulator does indeed show the simulator iphone but the 'Hello World' text does not show and the console log reports error

    └ jsio.js:699 Error: Could not import `.home.dave.CodeProjects.devkit.mygame.modules.devkit-core.src.build.native.native-ios`
                  	looked in:
                  		/usr/local/lib/node_modules/devkit/src/apps/home/dave/CodeProjects/devkit/mygame/modules/devkit-core/src/build/native/native-ios.js
                  		/usr/local/lib/node_modules/devkit/src/apps/home/dave/CodeProjects/devkit/mygame/modules/devkit-core/src/build/native/native-ios/index.js
                  	Import Stack:

Not surprising really as Linux isn't native ios, however there are also no details of how to configure and run devkit using android instead (which is supported on Linux - actually just running in the browser would be a start), I tried 

devkit debug native-android

and this time got 

   └ App.js:554 ApplicationNotFoundError at Function.loadAppFromPath [as loadFromPath] (/usr/local/lib/node_modules/devkit/src/apps/App.js)
        [build]    [error]  build failed
        [build]    [error]  ApplicationNotFoundError

and

        [build]    [error]  Cannot SET build info before buildInfoPath is set
        [build]    1.25 seconds elapsed
        [build]    [error]  Cannot SET build info before buildInfoPath is set
        [build]    [error]  Cannot SET build info before buildInfoPath is set

Thanks for any help
Cheers

Dave

**Comment by dave-watts** [comment]
ok, it only seems to work if you run as root!

sudo devkit init 
sudo devkit serve

(yes, both of them!)

**Comment by collingreen** [comment]
I would expect it 'only works as root' if you installed devkit with `sudo npm install devkit`. You definitely don't need root to run devkit, and you *definitely* shouldn't give random software root access.

**Comment by dave-watts** [comment]
If I trying installing devkit without root, this was the error

npm ERR! Please try running this command again as root/Administrator.

by the way the linux install link at https://github.com/gameclosure/devkit is broken

found the Linux wikki page, took option 2, option 1 still gave errors, but for some strange reason had to also chown 

/home/dave/tmp

maybe this was the problem!
