### ISSUE TITLE
jsio_compile.compiler Error

### ISSUE THREAD

**Issue by iozcelik** [gameclosure/devkit#239]
![captureq](https://cloud.githubusercontent.com/assets/10682780/9084324/38ad28a4-3b7b-11e5-8f2e-6249c650fa94.PNG)
Hi I'm new here. I tried to download helloworld demo but I always take an error like error could not import 'jsio_compile.compiler'. I looked documentation and I googled but there is no answer for me.
What's wrong on my computer?

**Comment by collingreen** [comment]
Are you using the gitbash shell? Did you follow the windows installation instructions exactly?

**Comment by iozcelik** [comment]
Yes, I follow exaclty. I installed gitbash, node.js,npm and Java SDK. I worried about their PATH. I dont know is it true or not. I dont have enough knowledge.

**Comment by collingreen** [comment]
Were there any errors along the way? Sometimes install errors with one of the tools or devkit itself can lead to confusing errors down the line if you miss them when they happen.

**Comment by iozcelik** [comment]
I solved this problem but I have new one now. Build is always failed. Why, I dont solve it.

$ devkit serve
        [serve]    serving at http://localhost:9200/ and http://10.1.1.161:9200/
  [jsioCompile]    jsio_compile "import .index, jsio.preprocessors.inlineSlice, jsio.preprocessors.import, jsio.preprocessors.cls, jsio.util.syntax" --env "browser" --cwd "C:\\Users\\İsmail\\AppData\\Roaming\\npm\\node_modules\\devkit\\src\\serve\\static\\" --appendImport "true" --path "[\"C:\\\\Users\\\\İsmail\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\devkit\\\\node_modules\\\\ff\\\\lib\\\\\",\"C:\\\\Users\\\\İsmail\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\devkit\\\\node_modules\\\\printf\\\\lib\",\"C:\\\\Users\\\\İsmail\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\devkit\\\\node_modules\\\\jsio\\\\packages\"]" --pathCache "{\"squill\":\"C:\\\\Users\\\\İsmail\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\devkit\\\\node_modules\\\\squill\\\\\"}" --environment "browser" --includeJsio "true" --jsioPath "C:\\Users\\İsmail\\AppData\\Roaming\\npm\\node_modules\\devkit\\node_modules\\jsio\\packages" --preprocessors "[\"import\",\"cls\",\"logger\"]"
Error: ENOENT, stat 'C:\Users\İsmail\helloworld\resources\icons\defaultIcon.png'
    at Error (native)
  [build-queue]    starting build C:\Users\İsmail\citySimu native-ios
        [build]    starting build at Tue Sep 01 2015 12:27:54 GMT+0300 (Turkey Daylight Time)
         [apps]    C:\Users\İsmail\citySimu\manifest.json
       [devkit]
        [build]    Prebuild phase completed for demo isometric
                        build for: native-ios           scheme: debug
       [devkit]
                    --- start config ---
                                        appPath: C:\Users\İsmail\citySimu
                                          debug: true
                                         scheme: debug
                                         target: native-ios
                                    imports:
                                              0: devkit-simulator-client
                                              1: devkit-view-inspector
                                              1: devkit-view-inspector
                                     schemePath: build\debug
                                     outputPath: C:\Users\İsmail\citySimu\build\debug\simulator
                                   jsioPath:
                                       jsioPath: C:\Users\İsmail\citySimu\build\debug\simulator
                                clientPaths:
                        devkit-simulator-client: C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\modules\devkit-simulator-client\client
                          devkit-view-inspector: C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\modules\devkit-view-inspector\client
                          devkit-view-inspector: C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\modules\devkit-view-inspector\client
                                     sdkVersion: 3.0.1
                                      isTestApp: undefined
                                    isSimulated: true
                                  simulator:
                                       deviceId: sim1
                                     deviceType: iphone6
                                     deviceInfo: {"name":"iPhone 6","target":"native-ios","devicePixelRatio":2,"canRotate":true,"canResize":false,"height":1334,"width":7 …
                                           port: undefined
                                        modules: ["devkit-simulator-client","devkit-view-inspector"]
                                        modules: ["devkit-simulator-client","devkit-view-inspector"]
                                   spriteImages: true
                                             ip: 10.1.1.161
                                 localServerURL: 10.1.1.161:9200
                                     serverName: local
                             outputResourcePath: C:\Users\İsmail\citySimu\build\debug\simulator
                                         studio: gameclosure.com
                                        version: debug
                                       compress: false
                                          appID: 361ba0403cd14216939ee847bc8baa8b
                                 localBuildPath: build\debug\simulator
                                       bundleID: example.bundle
                                    packageName: com.gameclosure.demoIsometricGame
                                          isIOS: true
                                         repack: undefined
                                           open: true
                                         reveal: undefined
                                  provisionPath: undefined
                                signingIdentity: undefined
                                  enableLogging: false
                                    browser:
                                    embedSplash: false
                                     embedFonts: false
                                 appleTouchIcon: false
                         appleTouchStartupImage: false
                                          frame: {}
                                         canvas: {}
                                           copy: []
                                       headHTML: []
                                       bodyHTML: []
                                     footerHTML: []
                                 webAppManifest: {"name":"demo isometric","icons":[],"start_url":"index.html","display":"standalone"}
                                        baseURL:
                                        baseURL:
                                directories:
                                              0: {"src":"C:\\Users\\İsmail\\citySimu\\resources","target":"resources"}
                                              0: {"src":"C:\\Users\\İsmail\\citySimu\\resources","target":"resources"}
                    --- end config ---
 [jsio-compile]    compiling import devkit.browser.launchClient, devkit-simulator-client, devkit-view-inspector

Error loading module:
     [[ import jsio_compile.compiler ]]
     requested by: ./<initial file>
     current directory: C:\Users\İsmail\citySimu
   Error: Could not import `jsio_compile.compiler`
        looked in:
                C:\Users\İsmail\citySimu/C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\compilers/jsio_compile/compiler.js
                C:\Users\İsmail\citySimu/C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\compilers/jsio_compile/compiler/index.js
        Import Stack:

      at loadModule (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:699:17)
      at ENV_node.loadModule (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:468:18)
      at _require (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:862:34)
      at C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:88:27
      at compile (C:\Users\İsmail\citySimu\modules\devkit-core\src\build\common\jsCompiler.js:96:20)
      at tryCatcher (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\util.js:26:23)
      at ret (eval at <anonymous> (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:13:39)
      at C:\Users\İsmail\citySimu\modules\devkit-core\src\build\browser\index.js:122:11
      at tryCatcher (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\util.js:26:23)
      at Promise._settlePromiseFromHandler (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:503:31)
      at Promise._settlePromiseAt (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:577:18)
      at Promise._settlePromises (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:693:14)
      at Async._drainQueue (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:123:16)
      at Async._drainQueues (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:15:14)
      at processImmediate [as _immediateCallback] (timers.js:367:17)
      [spriter]    spriter --no-clean --cache-file "spritercache-a1c7997eb3c0d69965fc71327512ec54" --scale "1" --dir "C:\Users\İsmail\citySimu\resources/" --output "C:\Users\İsmail\citySimu\build\debug\simulator\spritesheets" --target "native-ios" --binaries "undefined" --is-simulator "true" --spriter-png-fallback "false"
        [build]
⤷  processImmediate [as _immediateCallback] (timers.js:367)
 ⤷  Immediate.Async.drainQueues [as _onImmediate] (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:15)
  ⤷  Async._drainQueues (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:133)
   ⤷  Async._drainQueue (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\async.js:123)
    ⤷  Promise._settlePromises (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:693)
     ⤷  Promise._settlePromiseAt (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:577)
      ⤷  Promise._settlePromiseFromHandler (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promise.js:503)
       ⤷  tryCatcher (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\util.js:26)
        ⤷  undefined (C:\Users\İsmail\citySimu\modules\devkit-core\src\build\browser\index.js:122)
         ⤷  ret (eval at <anonymous> (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\promisify.js:163)
          ⤷  tryCatcher (C:\Users\İsmail\AppData\Roaming\npm\node_modules\devkit\node_modules\bluebird\js\main\util.js:26)
           ⤷  compile (C:\Users\İsmail\citySimu\modules\devkit-core\src\build\common\jsCompiler.js:96)
            ⤷  undefined (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:88)
             ⤷  _require (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:862)
              ⤷  ENV_node.loadModule (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:468)
               ⤷  loadModule (C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\packages\jsio.js:699)
               Error: Could not import `jsio_compile.compiler`
                        looked in:
                                C:\Users\İsmail\citySimu/C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\compilers/jsio_compile/compiler.js
                                C:\Users\İsmail\citySimu/C:\Users\İsmail\citySimu\modules\devkit-core\node_modules\jsio\compilers/jsio_compile/compiler/index.js
                        Import Stack:


                  build failed

**Comment by iozcelik** [comment]
I solved this problem with change the Python version.

**Comment by jwilm** [comment]
Thank you for sharing your solution!
