### ISSUE TITLE
java runtime 

### ISSUE THREAD

**Issue by andy-dev** [gameclosure/devkit#241]
hi!

I am starting to use game closure. I tried the hello world app but in chorme i am getting the intall java runtime enviroment. (I did and clicked to Enable NPAPI). I am still getting the same error,

Did I miss something, Im guessing its something very small.

**Comment by collingreen** [comment]
Hi Andy,

I'm not sure what you are running into there. Can you give me a little bit more info about what you have done so far? Do you have java installed? You can check by opening your terminal and running `java -version`

**Comment by andy-dev** [comment]
Hi,

Thank you so much for you quick reply. I was able to figure it out, so I had java installed but I also needed the Java Development Kit (JDK). 

Thanks again
