### ISSUE TITLE
devkit serve doesnt shown apps

### ISSUE THREAD

**Issue by iozcelik** [gameclosure/devkit#242]
Hello, everything is fine at setup for me until try to install helloworld app. I typed devkit serve and open my localhost. But my browser is empty. I dont understand why. Has anybody an idea?
![capture](https://cloud.githubusercontent.com/assets/10682780/9631771/d995906e-518b-11e5-8807-08455ff798fc.PNG)

**Comment by dongminkim** [comment]
I have the same problem.
I had been following the tutorial, then I have got an empty screen on my chrome.
Chrome's dev console shows this error:
![screenshot](https://cloud.githubusercontent.com/assets/1652790/9632154/6bb1ec0c-51c0-11e5-8294-796e1c7de96a.png)

**Comment by jwilm** [comment]
Does this happen after running `devkit init` for a new game?

**Comment by iozcelik** [comment]
Yes, after installation of devkit, I want to try hello world app. So I typed devkit init helloworld then devkit serve but nothing works.

**Comment by jwilm** [comment]
@mgh any ideas? I think you were building on windows recently.

**Comment by iozcelik** [comment]
Yes, I am using Windows 8.1.

**Comment by dongminkim** [comment]
FYI,

I've run `devkit init helloworld`, and then `devkit serve`.
I'm using Mac OS X 10.10.5

**Comment by iozcelik** [comment]
For information, I can show my apps on git bash like this:
![capture](https://cloud.githubusercontent.com/assets/10682780/9677613/e0960e48-52e4-11e5-906f-5acf250cc9cd.PNG)

**Comment by Pengeszikra** [comment]
I have same error ... ( windows 8  )

at chrome console found ff throw some error 

ff.js:411 Uncaught TypeError: std.uri.relativeTo is not a functionexports.get @ cssLoad.js:39GLOBAL.overview.Overview.parent @ apps.js:28SuperGroup._execNextStep @ ff.js:365(anonymous function) @ ff.js:443

**Comment by Pengeszikra** [comment]
Possible this problem couse my user folder name :: \Users\Vívó Péter .. so it is contain space and few isin't ascii char.

**Comment by Pengeszikra** [comment]
fix at devkit\node_modules\squill\cssLoad.js line 39
```javascript
var url = ( std && std.uri && std.uri.relativeTo ) ? std.uri.relativeTo(opts.url, window.location.toString()) :  window.location.origin+opts.url 
```

**Comment by mgh** [comment]
@iozcelik @dongminkim @Pengeszikra can you try the latest devkit version and see if that fixes the problem?  Run `npm upgrade -g devkit` to upgrade.  Thanks!

**Comment by iozcelik** [comment]
Yes, and thanks. I handled this problem and pyhton problem. But now, I have new one. warning MSB8003: Could not find WindowsSDKDir variable from the registry. TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. I try to solve this issue.

**Comment by iozcelik** [comment]
Finally, it's done! I use VS2015 so some options are not coming by default. So I modify my VS2015. Then I try and it is work. Thanks everyone.

**Comment by mgh** [comment]
good to hear you got it working!  I just pushed a new devkit version also, v3.1.1, that *actually* fixes the uri issue. @lozcelik, is there anything in your VS2015 config that might be relevant for others?

**Comment by dongminkim** [comment]
@mgh It works after `npm upgrade -g devkit`. Thank you.
