### ISSUE TITLE
missing debug-api module in devkit-core

### ISSUE THREAD

**Issue by paralleloide** [gameclosure/devkit#253]
I just completed the devkit install on osx. Then running the helloworld sample in my chrome browser bring some error in the console. It seems i'm missing some debug-api folder.

`{"message":"Cannot find module '/Users/seub/devkit/helloworld/modules/devkit-core/src/build/debug-api'","stack":"Error: Cannot find module '/Users/seub/devkit/helloworld/modules/devkit-core/src/build/debug-api'\n    at Function.Module._resolveFilename (module.js:336:15)\n    at Function.Module._load (module.js:278:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at loadExtensions (/usr/local/lib/node_modules/devkit/src/serve/appRoutes.js:171:22)\n    at null.<anonymous> (/usr/local/lib/node_modules/devkit/src/serve/appRoutes.js:156:12)\n    at Array.forEach (native)\n    at init (/usr/local/lib/node_modules/devkit/src/serve/appRoutes.js:154:26)\n    at new <anonymous> (/usr/local/lib/node_modules/devkit/node_modules/jsio/packages/base.js:99:70)\n    at /usr/local/lib/node_modules/devkit/src/serve/appRoutes.js:231:26\n    at tryCatcher (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:245:10)\n    at Async._drainQueue (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:133:10)"}`

how can i get these debug resources ?

**Comment by yofreke** [comment]
What commands did you run to create the helloworld project?  Does running `devkit install` inside of the project directory fix your problem?

**Comment by paralleloide** [comment]
its been a while since this... thanks for your reply, but i fixed it. If i remember well, it was a directory owning issue. (should have closed this issue back then...)
