### ISSUE TITLE
basil testapp native-android fails

### ISSUE THREAD

**Issue by j-klassen** [gameclosure/devkit#84]
I'm using release 0.1.30 and running basil testapp native-android and I get the following log:
(I have tried cloning native-android manually as well but the result is the same.)
Any help would be appreciated.

```
$ basil testapp native-android
   [testapp]    Launching Test App: native-android
      [make]   android update project -p TeaLeaf --target android-15 --subprojects
      [make]    [warn]  Invalid number of parameters

      [make]   Updated project.properties
      [make]   Updated local.properties
      [make]   Updated file C:\Users\Jake\github\devkit\addons\native-android\TeaLeaf\proguard-proje
ct.txt
      [make]   android update project -p GCTestApp --target android-15 --subprojects
      [make]    [warn]  Invalid number of parameters

      [make]   Updated project.properties
      [make]   Updated local.properties
      [make]   Updated file C:\Users\Jake\github\devkit\addons\native-android\GCTestApp\proguard-pro
ject.txt
      [make]   ndk-build -C TeaLeaf -Bj8 RELEASE=0 JSPROF=1 GPROF=0 V8SYMBOLS=0
      [make]   Android NDK: WARNING: APP_PLATFORM android-14 is larger than android:minSdkVersion 8
in ./AndroidManifest.xml
      [make]   make[1]: Entering directory `c:/Users/Jake/github/devkit/addons/native-android/TeaLea
f'
      [make]   Gdbserver      : [arm-linux-androideabi-4.6] libs/armeabi/gdbserver
      [make]   Gdbsetup       : libs/armeabi/gdb.setup
      [make]   Gdbserver      : [arm-linux-androideabi-4.6] libs/armeabi-v7a/gdbserver
      [make]   Gdbsetup       : libs/armeabi-v7a/gdb.setup
      [make]   "Compile++ thumb : tealeaf <= js.cpp
      [make]   "Compile++ thumb : tealeaf <= js_animate.cpp
      [make]   "Compile++ thumb : tealeaf <= js_build.cpp
      [make]   "Compile++ thumb : tealeaf <= js_console.cpp
      [make]   "Compile++ thumb : tealeaf <= js_context.cpp
      [make]   "Compile++ thumb : tealeaf <= js_device.cpp
      [make]   "Compile++ thumb : tealeaf <= js_dialog.cpp
      [make]   "Compile++ thumb : tealeaf <= js_events.cpp
      [make]    [warn]  jni/js/js.cpp: In function 'void log_error(char const*)':
      [make]   jni/js/js.cpp:173:3: error: format not a string literal and no format arguments [-Wer
ror=format-security]

      [make]   "Compile++ thumb : tealeaf <= js_gc.cpp
      [make]   "Compile++ thumb : tealeaf <= js_haptics.cpp
      [make]   "Compile++ thumb : tealeaf <= js_input_prompt.cpp
      [make]    [warn]  cc1plus.exe: all warnings being treated as errors
      [make]

      [make]    [warn]  make[1]: *** [obj/local/armeabi/objs-debug/tealeaf/js/js.o] Error 1

      [make]    [warn]  make[1]: *** Waiting for unfinished jobs....

      [make]   make[1]: Leaving directory `c:/Users/Jake/github/devkit/addons/native-android/TeaLeaf
'
      [make]    [warn]  make: *** [all] Error 2

      [make]    [error]  (make exited with code 2)
ERROR 2
```

**Comment by jgamao** [comment]
I think I also got that issue.

I can't create a release for my app in my ubuntu 14.04.

There are build errors when I command devkit release native-android:

[ndk-build] ndk-build -j 8 RELEASE=1
[android] android create project --target android-15 --name calamity_run --path /home/joselito/wt-calamityrun/build/release/native-android --activity calamity_runActivity --package com.wetalkdirect.studio.calamity_run
Android NDK: WARNING: APP_PLATFORM android-15 is larger than android:minSdkVersion 8 in ./AndroidManifest.xml

[ndk-build] Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries

[ndk-build] Android NDK: WARNING:jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries

[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_animate.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_build.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_console.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_context.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_device.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_dialog.cpp
[ndk-build] [armeabi] Compile++ thumb: tealeaf <= js_events.cpp
[ndk-build] jni/js/js_animate.cpp:17:24: fatal error: core/types.h: No such file or directoryIn file included from jni/js/js_events.cpp:17:0:
jni/js/js_events.h:17:30: fatal error: core/util/detect.h: No such file or directory

compilation terminated.
compilation terminated.
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_events.o] Error 1
[ndk-build] make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_animate.o] Error 1
[ndk-build] jni/js/js.cpp:21:30: fatal error: core/util/detect.h: No such file or directory
compilation terminated.
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js.o] Error 1
[ndk-build] In file included from jni/js/js_dialog.h:18:0,
from jni/js/js_dialog.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
In file included from jni/js/js_build.h:17:0,
from jni/js/js_build.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_build.o] Error 1
[ndk-build] In file included from jni/js/js_context.h:18:0,
from jni/js/js_context.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
[ndk-build] In file included from jni/js/js_device.h:15:0,
from jni/js/js_device.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
compilation terminated.
[ndk-build] In file included from jni/js/js_console.h:18:0,
from jni/js/js_console.cpp:17:
jni/js/js.h:18:26: fatal error: core/core_js.h: No such file or directory
[ndk-build] compilation terminated.
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_device.o] Error 1
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_console.o] Error 1
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_dialog.o] Error 1
[ndk-build] make: *** [obj/local/armeabi/objs-debug/tealeaf/js/js_context.o] Error 1
[build] [error] build failed
[build] [error] 2
[build] 2 minutes, 17.59 seconds elapsed
Error: Project folder '/home/joselito/wt-calamityrun/build/release/native-android' is not empty. Please consider using 'android update' instead.
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/src/com/wetalkdirect/studio/calamity_run
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/src/com/wetalkdirect/studio/calamity_run/calamity_runActivity.java
Created directory /home/joselito/wt-calamityrun/build/release/native-android/res
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/bin
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/libs
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/values
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/res/values/strings.xml
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/layout
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/res/layout/main.xml
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-hdpi
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-mdpi
[android] Created directory /home/joselito/wt-calamityrun/build/release/native-android/res/drawable-ldpi
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/AndroidManifest.xml
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/build.xml
[android] Added file /home/joselito/wt-calamityrun/build/release/native-android/proguard-project.txt
[android] android update project --target android-15 --path /home/joselito/wt-calamityrun/build/release/native-android --library ../../../modules/devkit-core/modules/native-android/TeaLeaf
Resolved location of library project to: /home/joselito/wt-calamityrun/modules/devkit-core/modules/native-android/TeaLeaf
[android] Updated project.properties
[android] Updated local.properties
[android] Updated file /home/joselito/wt-calamityrun/build/release/native-android/proguard-project.txt
[native-android] No plugin XML to inject
[native-android] Applying final XSL transformation
[native-android] [error] settings for AndroidManifest: value for icons is not a string
[jvmtools] connected to localhost:35765
